// API 类型兼容导出入口。新代码必须从 common/search/resource/auth 等领域类型文件导入。

export type { ApiResponse, ErrorResponse, HealthResponse, SuccessResponse } from '@/types/common';
export { CloudType } from '@/types/search';
export type {
  CloudTypeValue,
  FilterConfig,
  Link,
  MergedLink,
  MergedLinks,
  SearchParams,
  SearchRequest,
  SearchResponse,
  SearchProgressiveEvent,
  SearchProgressiveEventType,
  SearchResult,
  SearchSourceWarning,
} from '@/types/search';
export type {
  ResourceAction,
  ResourceAccessMode,
  ResourceCapabilities,
  ResourceDetail,
  ResourceDetailRouteState,
  ResourceFacets,
  ResourceLink,
  ResourceObject,
  ScanTransferRefreshRequest,
  ScanTransferRefreshResponse,
  ScanTransferInfo,
  ResourceSource,
} from '@/types/resource';
export type {
  AdminLoginRequest,
  AdminLoginResponse,
  APIKeyInfo,
  APIKeyInfoResponse,
  BatchCreateRequest,
  BatchCreateResult,
  BatchExtendRequest,
  BatchOperationItem,
  BatchOperationResult,
  CreateAPIKeyRequest,
  LoginRequest,
  LoginResponse,
  LoginWithRememberRequest,
  LoginWithRememberResponse,
  RefreshTokenRequest,
  RefreshTokenResponse,
  RegisterRequest,
  RegisterResponse,
  RevokeRefreshTokenRequest,
  UpdateAPIKeyRequest,
  VerifyResponse,
} from '@/types/auth';
export type {
  AdminDialogMode,
  AdminTagListResponse,
  AdminTagOption,
  AdminTagScope,
  CreateAdminTagRequest,
  CreateAdminTagResponse,
  DeleteAdminTagResponse,
  UpdateAdminTagRequest,
  UpdateAdminTagResponse,
} from '@/types/admin';
export type {
  BatchPluginOperationError,
  BatchPluginOperationResponse,
  BatchPluginStatusRequest,
  CloudTypeConfig,
  PluginCatalogInstall,
  PluginCatalogResponse,
  PluginConfigField,
  PluginHealthSnapshot,
  PluginInfo,
  PluginManifestPayload,
  PluginUIMetadata,
  ResourceDescriptor,
} from '@/types/plugin';
export type {
  SearchKeywordStat,
  SearchMetricError,
  SearchObservabilitySnapshot,
  SystemConfig,
  SystemInfoResponse,
  SystemStats,
} from '@/types/system';
export type {
  BatchChannelOperationError,
  BatchChannelOperationResponse,
  BatchChannelStatusRequest,
  BatchDeleteChannelsRequest,
  ChannelHealthSummary,
  ListTGChannelsResponse,
  TGChannel,
} from '@/types/channel';
export type {
  AdminUserStats,
  BatchDeleteUsersRequest,
  BatchUpdateRoleRequest,
  BatchUserOperationError,
  BatchUserOperationResult,
  CreateUserRequest,
  CreateUserResponse,
  ListUsersRequest,
  ListUsersResponse,
  ResetPasswordRequest,
  SetUserStatusRequest,
  UpdateUserRequest,
  UserInfo,
} from '@/types/user';
export type {
  Announcement,
  AnnouncementFeatureEnabledResponse,
  AnnouncementLifecycleStatus,
  AnnouncementPriority,
  AnnouncementReadStatus,
  CreateAnnouncementRequest,
  ListAnnouncementsFilters,
  ListAnnouncementsResponse,
  SetAnnouncementFeatureEnabledRequest,
  SetAnnouncementStatusRequest,
  UpdateAnnouncementRequest,
} from '@/types/announcement';
